# Generated by Django 3.2.7 on 2022-03-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='My_team')),
                ('name', models.CharField(max_length=75)),
                ('profession', models.CharField(max_length=75)),
            ],
        ),
    ]
